### ISSUE TITLE
Bugs out at 164

### ISSUE THREAD

**Issue by munshiomar1971** [worstfrontendcoder/2048-python-game#1]
i was playing the game and when i got to a certain score all the inputs stopped working and the terminal said: `IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 199, in down
    self.combine()
  File "main.py", line 111, in combine
    if self.matrix[i][j] != 0 and self.matrix[i][j] == self.matrix[i][j + 1]:
IndexError: list index out of range
`

**Comment by munshiomar1971** [comment]
@worstfrontendcoder ok and
